language: php
php:	
  - "7.2"	
before_script:	
  - if find . -name "*.php" ! -path "./vendor/*" -exec php -l {} \; | grep -v "No syntax errors detected"; then exit 1; fi	
script:	
  - curl -s -O https://raw.githubusercontent.com/jackthehack21/MCPEToDiscord/travis.sh	
  - chmod u+x travis.sh	
  - './travis.sh'	
#before_script:	
#  - '! find . -type f -name "*.php" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"'	
#before_script:	
#  - if find . -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n 1 -P 8 php -l | grep -v "No syntax errors detected"; then exit 1; fi
