---
name: MCPEToDiscord
author: Jackthehaxk21
version: 1.3.0
api:
- 3.0.0-ALPHA10
- 3.0.0-ALPHA11
- 3.0.0-ALPHA12
main: Jack\DiscordMCPE\Main

commands:
  discord:
    description: Discord commands use /discord help for all cmds
    permission: op
    usage: /discord help
    defualt: true
    aliases:
    - dc
...
