---
name: MCPEToDiscord
author: Jackthehaxk21
version: 1.3.2
api:
- 3.0.0
- 3.0.1
- 3.0.2
- 3.0.3
main: Jack\DiscordMCPE\Main

commands:
  discord:
    description: Discord commands use /discord help for all cmds
    permission: op
    usage: /discord help
    defualt: true
    aliases:
    - dc
...
