---
name: MCPEToDiscord
author: Jackthehaxk21
version: 1.4
api:
- 3.0.0
- 3.1.1
main: Jack\DiscordMCPE\Main

commands:
  discord:
    description: Discord commands use /discord help for all cmds
    permission: op
    usage: /discord help
    defualt: true
    aliases:
    - dc
...
